apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-monitor-2
  namespace: poc-mariadb-maxscale-external
spec:
  mariaDbRef:
    name: mariadb-2
  privileges:
    - "BINLOG ADMIN"
    - "CONNECTION ADMIN"
    - "EVENT"
    - "PROCESS"
    - "PROCESS"
    - "READ_ONLY ADMIN"
    - "RELOAD"
    - "REPLICA MONITOR"
    - "REPLICATION CLIENT"
    - "REPLICATION SLAVE ADMIN"
    - "REPLICATION SLAVE"
    - "SELECT"
    - "SET USER"
    - "SHOW DATABASES"
    - "SLAVE MONITOR"
    - "SUPER"
  database: "*"
  table: "*"
  username: maxscale-monitor
  grantOption: false
  host: "%"
  retryInterval: 5s
