apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-0
  namespace: poc-mariadb-maxscale-external
spec:
  image: mariadb:10.6.9
  imagePullPolicy: IfNotPresent

  rootPasswordSecretKeyRef:
    name: mariadb-root-user
    key: password
    generate: true

  maxScaleRef:
    name: maxscale

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-generic-user
    key: password
    generate: true

  storage:
    size: 1Gi

  # NB: Remove "max_connections=10" in production

# myCnf: |
# [mariadb]
# server-id=1
# server_id=1
# bind-address=0.0.0.0
# log_bin=mysqld-bin
# explicit_defaults_for_timestamp
# skip-name-resolve
# ignore_db_dirs=lost+found
# max_allowed_packet=16M
# character-set-server=UTF8
# collation-server=utf8_general_ci
# relay_log=mysqld-relay-bin
# max_connections=10

  myCnf: |
    [mysqld]
    server-id=1
    log_bin=mysqld-bin
    log-slave-updates
    general_log = on
    general_log_file = /var/log/mysql/mysql.log
    log_error = /var/log/mysql/mysql_error.log
    slow_query_log = on
    slow_query_log_file = /var/log/mysql/mysql_slow.log
    long_query_time = 3
    default_time_zone='+00:00'
    max_connections=1000
    max_statement_time=120
    wait_timeout=600
    performance_schema=ON
    max_digest_length=4096
    performance_schema_max_digest_length=4096
    performance_schema_max_sql_text_length=4096
    performance-schema-consumer-events-statements-current=ON
    performance-schema-consumer-events-waits-current=ON
    performance-schema-consumer-events-statements-history-long=ON
    performance-schema-consumer-events-statements-history=ON
    explicit_defaults_for_timestamp='ON'
    collation_server=utf8_general_ci
    init_connect=''
    character_set_server=utf8
    sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    [mysqld_safe]
    log_error = /var/log/mysql/mysql_error.log