# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/HA.md#topologies
# https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_replication_full.yaml

apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-semisync
  namespace: poc-mariadb-semisync
spec:
  image: mariadb:10.6.9
  imagePullPolicy: IfNotPresent

  rootPasswordSecretKeyRef:
    name: mariadb-root-user
    key: password
    generate: true

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-generic-user
    key: password
    generate: true

  replicas: 3

  replication:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    replica:
      waitPoint: AfterSync
      gtid: CurrentPos
      replPasswordSecretKeyRef:
        name: mariadb-root-user
        key: password
      connectionTimeout: 10s
      connectionRetries: 10
      syncTimeout: 10s
    syncBinlog: true
    probesEnabled: true

  storage:
    size: 1Gi

  # NB: Remove "max_connections=10" in production
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
    log_bin=/var/log/mysql/mysql-bin.log
    explicit_defaults_for_timestamp
    ignore_db_dirs=lost+found
    max_connections=10

  affinity:
    antiAffinityEnabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  # metrics:
  #   enabled: true
