# NB: this is a simplified version of a MariaDB installation, it' meant for testing purposes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-app
  namespace: poc-mariadb-maxscale-external
  labels:
    app: mariadb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6.9
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Password1!"
