# k get pod maxscale-metrics-b46657d65-vcxb5 -n poc-mariadb-maxscale-external -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.mariadb.com/config: e4f95e78b0712a456e2091e4e66d8e44a1a25b672a091f57cba401c9b5165617
  creationTimestamp: "2024-10-14T07:08:02Z"
  generateName: maxscale-metrics-b46657d65-
  labels:
    app.kubernetes.io/instance: maxscale-metrics
    app.kubernetes.io/name: exporter
    pod-template-hash: b46657d65
  name: maxscale-metrics-b46657d65-vcxb5
  namespace: poc-mariadb-maxscale-external
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: maxscale-metrics-b46657d65
    uid: 80185cd6-d079-4738-a8c2-8e3b5d2714e3
  resourceVersion: "2045"
  uid: dd5492ab-cc3b-4487-a0ee-7c38516da135
spec:
  affinity: {}
  containers:
  - args:
    - --config=/etc/config/exporter.cnf
    image: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi:v0.0.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9105
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: exporter
    ports:
    - containerPort: 9105
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9105
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/config/
      name: config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2fwnq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-skytest-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    secret:
      defaultMode: 420
      secretName: maxscale-metrics-config
  - name: kube-api-access-2fwnq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-14T07:08:02Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-14T07:08:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-14T07:08:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-14T07:08:02Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f196571e7e59f4257db5cd0fd18cabb4bf276d4a0bb5618af541e5ef60ae9dd4
    image: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi:v0.0.1
    imageID: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi@sha256:9312d49ce245feebba5cc2788a0e5c8b6982f9f6eefe02c24b0901592274ef9f
    lastState: {}
    name: exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-10-14T07:08:10Z"
  hostIP: 172.18.0.3
  phase: Running
  podIP: 10.42.3.8
  podIPs:
  - ip: 10.42.3.8
  qosClass: BestEffort
  startTime: "2024-10-14T07:08:02Z"
