# k get servicemonitor maxscale-metrics -n poc-mariadb-maxscale-external -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2024-10-14T07:08:02Z"
  generation: 1
  labels:
    release: prometheus
  name: maxscale-metrics
  namespace: poc-mariadb-maxscale-external
  ownerReferences:
  - apiVersion: k8s.mariadb.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: MaxScale
    name: maxscale
    uid: 7bf4135b-a055-4815-a702-fbdefa29f2d2
  resourceVersion: "2030"
  uid: bec9d15b-fd6b-451d-bfaa-c63afc85864f
spec:
  endpoints:
  - metricRelabelings:
    - action: replace
      replacement: maxscale-0.maxscale-internal.poc-mariadb-maxscale-external.svc.cluster.local
      sourceLabels:
      - instance
      targetLabel: instance
    - action: replace
      replacement: maxscale-0
      sourceLabels:
      - target
      targetLabel: target
    params:
      target:
      - maxscale-0.maxscale-internal.poc-mariadb-maxscale-external.svc.cluster.local:8989
    path: /probe
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - poc-mariadb-maxscale-external
  selector:
    matchLabels:
      app.kubernetes.io/instance: maxscale-metrics
      app.kubernetes.io/name: exporter
