# k get servicemonitor maxscale-metrics -n poc-mariadb-maxscale-external -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2024-10-14T12:15:28Z"
  generation: 1
  labels:
    release: prometheus
  name: maxscale-metrics
  namespace: poc-mariadb-maxscale-external
  ownerReferences:
  - apiVersion: k8s.mariadb.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: MaxScale
    name: maxscale
    uid: 73af1754-c431-496a-9d3e-3f751339b6ac
  resourceVersion: "2090"
  uid: 755c5cb4-d454-4d61-b5e0-2ea78901a344
spec:
  endpoints:
  - metricRelabelings:
    - action: replace
      replacement: maxscale-0.maxscale-internal.poc-mariadb-maxscale-external.svc.cluster.local
      sourceLabels:
      - instance
      targetLabel: instance
    - action: replace
      replacement: maxscale-0
      sourceLabels:
      - target
      targetLabel: target
    params:
      target:
      - maxscale-0.maxscale-internal.poc-mariadb-maxscale-external.svc.cluster.local:8989
    path: /probe
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - poc-mariadb-maxscale-external
  selector:
    matchLabels:
      app.kubernetes.io/instance: maxscale-metrics
      app.kubernetes.io/name: exporter