apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: maxscale-admin-0
  namespace: poc-mariadb-maxscale-external
spec:
  name: maxscale-admin
  mariaDbRef:
    name: mariadb-0
  passwordSecretKeyRef:
    name: maxscale-admin
    key: password
  maxUserConnections: 20
  host: "%"
  retryInterval: 5s
  requeueInterval: 60s
