apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-client-0
  namespace: poc-mariadb-maxscale-external
spec:
  mariaDbRef:
    name: mariadb-0
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: maxscale-client
  grantOption: false
  host: "%"
  retryInterval: 5s
  requeueInterval: 60s
