apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.maxscale.maxscale_deployment_name }}-apptest
 namespace: {{ .Values.maxscale.namespace }}

 labels:
   app: maxscale-apptest
spec:
 replicas: 1
 selector:
   matchLabels:
     app: maxscale-apptest
 template:
   metadata:
     labels:
       app: maxscale-apptest
   spec:
     containers:
     - name: fakeclient
       image: mysql
       command:
         - bash
         - "-c"
         - "sleep infinity"
