apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.maxscale.maxscale_configmap_name }}
  namespace: {{ .Values.maxscale.namespace }}

data:
  maxscale.cnf: |
    [maxscale]
    threads=auto
    admin_secure_gui=false
    admin_enabled=true
    config_sync_cluster=monitor
    config_sync_user=maxscalemonitor
    config_sync_password=monitorpassword

    [primary0]
    type=server
    address="mariadb-primary"
    port=3306
    protocol=MariaDBBackend

    [secondary0]
    type=server
    address="mariadb-secondary-0"
    port=3306
    protocol=MariaDBBackend

    [monitor]
    type=monitor
    module={{ .Values.maxscale.maxscale_monitor_module }}
    servers=primary0,secondary0
    failcount={{ .Values.maxscale.maxscale_fail_count }}
    auto_failover={{ .Values.maxscale.maxscale_auto_failover }}
    auto_rejoin={{ .Values.maxscale.maxscale_auto_rejoin }}
    monitor_interval={{ .Values.maxscale.maxscale_monitor_interval }}ms
    enforce_simple_topology={{ .Values.maxscale.enforce_simple_topology }}
    enforce_read_only_slaves={{ .Values.maxscale.enforce_read_only_slaves }}
    user={{ .Values.maxscale.monitor_user }}
    password={{ .Values.maxscale.monitor_password }}

    [RW-service]
    type=service
    router=readconnroute
    servers=primary0,secondary0
    router_options: {{ .Values.maxscale.router_options }}
    user={{ .Values.maxscale.service_user }}
    password={{ .Values.maxscale.service_password }}
    enable_root_user={{ .Values.maxscale.enable_root_user }}

    [RW-listener]
    type=listener
    service=RW-service
    protocol={{ .Values.maxscale.maxscale_router_protocol }}
    port=3306
