apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.maxscale.maxscale_service_name }}-gui
 namespace: {{ .Values.maxscale.namespace }}
spec:
 ports:
 - port: 8989
   name: maxscale-gui
 selector:
   app: maxscale
