apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: maxscale-monitor-1
  namespace: poc-mariadb-maxscale-external
spec:
  name: maxscale-monitor
  mariaDbRef:
    name: mariadb-1
  passwordSecretKeyRef:
    name: maxscale-monitor
    key: password
  maxUserConnections: 20
  host: "%"
  retryInterval: 5s
  requeueInterval: 60s
