apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-server-mysql-1
  namespace: poc-mariadb-maxscale-external
spec:
  mariaDbRef:
    name: mariadb-1
  privileges:
    - "SELECT"
  database: "mysql"
  table: "*"
  username: maxscale-server
  grantOption: false
  host: "%"
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-server-databases-1
  namespace: poc-mariadb-maxscale-external
spec:
  mariaDbRef:
    name: mariadb-1
  privileges:
    - "SHOW DATABASES"
  database: "*"
  table: "*"
  username: maxscale-server
  grantOption: false
  host: "%"
  retryInterval: 5s
