apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
  namespace: poc-maxscale
spec:
  image: mariadb/maxscale:24.02.2
  imagePullPolicy: IfNotPresent

  metrics:
    enabled: true
    serviceMonitor:
      prometheusRelease: prometheus

  servers:
    - name: mariadb-0
      address: mariadb-svc-0.poc-maxscale.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend
    - name: mariadb-1
      address: mariadb-svc-1.poc-maxscale.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend

  # https://mariadb.com/kb/en/mariadb-maxscale-24-readconnroute/
  services:
    - name: mx-router
      router: readconnroute
      params:
        router_options: "master"
        max_replication_lag: "3s"
        enable_root_user: "true"
        max_connections: "1000"
      listener:
        port: 3306
        protocol: MariaDBProtocol

  # https://mariadb.com/kb/en/mariadb-maxscale-24-readwritesplit/
  # services:
  #   - name: mx-router
  #     router: readwritesplit
  #     params:
  #       enable_root_user: "true"
  #       max_slave_connections: "0"
  #       master_failure_mode: "fail_instantly"
  #       master_accept_reads: "true"
  #     listener:
  #       port: 3306
  #       protocol: MariaDBProtocol

  monitor:
    name: mx-monitor
    module: mariadbmon
    interval: 1s
    params:
      auto_failover: "true"
      auto_rejoin: "true"
      enforce_simple_topology: "true"
      enforce_read_only_slaves: "true"
      failcount: "1"

  podSecurityContext:
    fsGroup: 995
    runAsUser: 0

  admin:
    port: 8989
    guiEnabled: true

  auth:
    generate: false
    adminUsername: maxscale-admin
    adminPasswordSecretKeyRef:
      name: maxscale-admin
      key: password
    deleteDefaultAdmin: true
    clientUsername: maxscale-client
    clientPasswordSecretKeyRef:
      name: maxscale-client
      key: password
    clientMaxConnections: 90
    serverUsername: maxscale-server
    serverPasswordSecretKeyRef:
      name: maxscale-server
      key: password
    serverMaxConnections: 90
    monitorUsername: maxscale-monitor
    monitorPasswordSecretKeyRef:
      name: maxscale-monitor
      key: password
    monitorMaxConnections: 90
    syncUsername: maxscale-sync
    syncPasswordSecretKeyRef:
      name: maxscale-sync
      key: password
    syncMaxConnections: 90

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 5

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 5
