apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-admin
  namespace: poc-mariadb-maxscale-internal
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "*"
  database: "*"
  table: "*"
  username: maxscale-admin
  grantOption: false
  host: "%"
  retryInterval: 5s
