apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-client
  namespace: poc-mariadb-maxscale-internal
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: maxscale-client
  grantOption: false
  host: "%"
  retryInterval: 5s
  requeueInterval: 60s
