apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-server-mysql
  namespace: poc-mariadb-maxscale-internal
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
  database: "mysql"
  table: "*"
  username: maxscale-server
  grantOption: false
  host: "%"
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-server-databases
  namespace: poc-mariadb-maxscale-internal
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SHOW DATABASES"
  database: "*"
  table: "*"
  username: maxscale-server
  grantOption: false
  host: "%"
  retryInterval: 5s
