apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: maxscale-sync
  namespace: poc-mariadb-maxscale-internal
spec:
  name: maxscale-sync
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: maxscale-sync
    key: password
  maxUserConnections: 20
  host: "%"
  retryInterval: 5s
  requeueInterval: 60s
