apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-sync
  namespace: poc-mariadb-maxscale-internal
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "CREATE"
    - "DROP"
  database: "mysql"
  table: "maxscale_config"
  username: maxscale-sync
  grantOption: false
  host: "%"
  retryInterval: 5s
